name: ibmi_fraud_detection
channels:
  - defaults
  - conda-forge
  - rocketce
dependencies:
  - python==3.9
  - onnxruntime=1.15.1
  - scikit-learn=1.2.0
  - sklearn-pandas
  - dill
  - pip
  - pip:
      - flask==3.0.0