apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-onnx-predictor-sa

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-application-onnx
  annotations: {}
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        autoscaling.knative.dev/max-scale: "1"
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/target: "1"
    spec:
      serviceAccountName: fraud-onnx-predictor-sa
      containers:
        - name: flask
          image: "quay.io/ajshedivy/demo-fraud-inference-app@sha256:77c95ce8952213795e5cffca5f2ce52ebd029c0a1beddf7d3083b161211ea6a6"
          imagePullPolicy: Always
          securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
          resources:
              limits:
                cpu: "1"
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 100Mi
          ports:
            - containerPort: 5000
              name: http1
              protocol: TCP