apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-predictor-app
  labels:
    app: fraud-predictor-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-predictor-app
  template:
    metadata:
      labels:
        app: fraud-predictor-app
      annotations:
        sidecar.istio.io/inject: "false" 
    spec:
      containers:
      - name: fraud-predictor-app
        image: quay.io/ajshedivy/demo-fraud-inference-app@sha256:b195e5f48931190231b01f11c71c0d33f084df9a8444eecdf1f85df160c33d59
        imagePullPolicy: Always
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
        ports:
        - containerPort: 5000
          name: http1
          protocol: TCP
        resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: fraud-predictor-app-service
spec:
  selector:
    app: fraud-predictor-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

--- 

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fraud-predictor-app-route
spec:
  to:
    kind: Service
    name: fraud-predictor-app-service
  port:
    targetPort: 5000

